### ISSUE TITLE
the publisher's name next to the extension name is a bit dim

### ISSUE THREAD

**Issue by singularitti** [radiolevity/neofloss#1]
Thank you for such a good extension. Just a quick question: the publisher's name next to the extension name is a bit dim and hard to read, is it on purpose, or is it a bug?

![image](https://user-images.githubusercontent.com/25192197/92041257-e80e5080-ed45-11ea-9f7f-4aaa99b1acfc.png)

**Comment by finnjames** [comment]
Thanks for pointing this out, it was definitely a bug. Fixed in v1.1.4.
