### ISSUE TITLE
Can we have the water mark text back?

### ISSUE THREAD

**Issue by singularitti** [radiolevity/neofloss#2]
![image](https://user-images.githubusercontent.com/25192197/92071930-085a0180-ed7e-11ea-9d5d-b836b5356e36.png)

![image](https://user-images.githubusercontent.com/25192197/92072012-3e978100-ed7e-11ea-848f-33571077eb61.png)

The missing watermark makes it feel a little empty in the middle. Is it possible to have it back?

**Comment by finnjames** [comment]
I would like to leave that as-is, but if you want those back just add the following to your `settings.json` file:
```json
"workbench.colorCustomizations": {
  "editorGroup.emptyBackground": "#0000",
}
```
