### ISSUE TITLE
Native bracket highlighting suggestion

### ISSUE THREAD

**Issue by ABS96** [radiolevity/neofloss#4]
Hello, thanks for the great theme!

I noticed that the 'Bracket Pair Colorizer 2' extension is listed as recommended in the Readme.
VS Code now supports bracket highlighting out of the box.

I thought I would create a PR where I:

- add the suggested bracket colors to the theme with the [new settings](https://code.visualstudio.com/api/references/theme-color#editor-colors) (that start with `editorBracketHighlight`)
- and remove the extension from the recommendations in the Readme

How do you feel about this idea?

**Comment by finnjames** [comment]
Sounds great, submit the PR and I'll take a look!
